# Generated by Django 5.0.14 on 2026-06-15 12:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_range_start', models.TimeField(default='08:00:00')),
                ('attendance_range_end', models.TimeField(default='10:00:00')),
                ('is_gate_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], default='PRESENT', max_length=15)),
                ('marked_by', models.CharField(choices=[('AUTO', 'Automatic (Face Recognition)'), ('MANUAL', 'Manual (Gateman)')], default='AUTO', max_length=15)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('gate_man', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
