# Generated by Django 5.0.14 on 2026-06-22 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceconfig',
            name='attendance_range_end',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='attendanceconfig',
            name='attendance_range_start',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
