# Generated by Django 5.0.14 on 2026-06-22 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendanceconfig_attendance_range_end_and_more'),
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='face_match_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='qr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='qr.dailyqr'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='qr_session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
