# Generated by Django 5.0.14 on 2026-06-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancerecord_face_match_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='checkout_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
