# Generated by Django 5.0.14 on 2026-06-15 12:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('DEFAULT', 'Default Fallback'), ('DAY_OF_WEEK', 'Day of Week Wise'), ('SPECIFIC_DATE', 'Specific Date Wise')], default='DEFAULT', max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('specific_date', models.DateField(blank=True, null=True, unique=True)),
                ('entry_start_time', models.TimeField(default='08:00:00')),
                ('entry_end_time', models.TimeField(default='18:00:00')),
                ('exit_start_time', models.TimeField(default='16:00:00')),
                ('exit_end_time', models.TimeField(default='22:00:00')),
            ],
            options={
                'ordering': ['-config_type', 'specific_date', 'day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='GateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], default='ENTRY', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_late', models.BooleanField(default=False)),
                ('verified_by', models.CharField(choices=[('FACE', 'Face Recognition'), ('QR', 'QR Code Pass'), ('MANUAL', 'Manual ID Search')], default='FACE', max_length=15)),
                ('gate_man', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_gate_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_records', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
