# Generated by Django 5.0.14 on 2026-06-22 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateconfig',
            name='entry_end_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='gateconfig',
            name='entry_start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='gateconfig',
            name='exit_end_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AlterField(
            model_name='gateconfig',
            name='exit_start_time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
