# Generated by Django 5.0.14 on 2026-06-15 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('face_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('face_image_public_id', models.CharField(blank=True, max_length=200, null=True)),
                ('face_encoding', models.JSONField(blank=True, null=True)),
                ('face_registered', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('late_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
