# Generated by Django 5.0.14 on 2026-06-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_attendance_blocked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='gate_pass_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
